export type AppRole =
  | 'CONDUCTOR'
  | 'ADMINISTRATIVO'
  | 'INVENTARIO'
  | 'SUPER_ADMIN'
  | 'ACTIVOS_FIJOS'
  | 'ADMIN' | 'OPERATOR' | 'VIEWER';

type Perm =
  | 'READ_INVENTORY'
  | 'WRITE_INVENTORY'
  | 'READ_ROUTES'
  | 'WRITE_ROUTES'
  | 'READ_SETTINGS'
  | 'WRITE_SETTINGS'
  | 'READ_USERS'
  | 'WRITE_USERS';

const MAP: Record<AppRole, Perm[]> = {
  CONDUCTOR: ['READ_ROUTES'],
  ADMINISTRATIVO: ['READ_INVENTORY'],
  INVENTARIO: ['READ_INVENTORY','WRITE_INVENTORY','READ_ROUTES','WRITE_ROUTES'],
  SUPER_ADMIN: ['READ_INVENTORY','WRITE_INVENTORY','READ_ROUTES','WRITE_ROUTES','READ_SETTINGS','WRITE_SETTINGS','READ_USERS','WRITE_USERS'],
  ACTIVOS_FIJOS: ['READ_INVENTORY','WRITE_INVENTORY','READ_ROUTES','WRITE_ROUTES','READ_SETTINGS','WRITE_SETTINGS','READ_USERS','WRITE_USERS'],
  ADMIN: ['READ_INVENTORY','WRITE_INVENTORY','READ_ROUTES','WRITE_ROUTES','READ_SETTINGS','WRITE_SETTINGS','READ_USERS','WRITE_USERS'],
  OPERATOR: ['READ_INVENTORY','WRITE_INVENTORY','READ_ROUTES','WRITE_ROUTES'],
  VIEWER: ['READ_INVENTORY'],
};

export function can(role: AppRole | undefined, perm: Perm) {
  if (!role) return false;
  return MAP[role]?.includes(perm) ?? false;
}
